#!/bin/bash
#Menu
IP=`dig +short myip.opendns.com @resolver1.opendns.com`
echo -e "------------ Selamat datang di server $IP -----------"
echo -e "Silakan ketik daftar perintah yang tersedia"
echo -e "========================DAFTAR MENU==========================="
echo -e "Apa yang ingin anda lakukan?"
echo -e "1)  Menampilkan daftar perintah yang tersedia	= menu"
echo -e "2)  Membuat akun SSH	= add"
echo -e "3)  Membuat akun trial	= trial"
echo -e "4)  Menghapus akun SSH	= del"
echo -e "5)  Cek user login	= cek"
echo -e "6)  DisConnect Multi Login = limit"
echo -e "Setelah limit harus service dropbear restart atau reboot"
echo -e "7)  Lock User Expire = user-expired"
echo -e "8)  Cek member SSH	= list"
echo -e "9)  Delete Akun SSH Dibaca baik-baik = user-del-exp"
echo -e "10)  Restart service dropbear,squid3,dll	= restart"
echo -e "11)  Reboot VPS	= reboot"
echo -e "12)  Speedtest VPS	= speedtest"
echo -e "13) Cek Kualitas VPS	= bench-network"
echo -e "14) Cek RAM VPS	= ps-mem"
echo -e "15) informasi tentang script auto install	= about"
echo -e "=========================THORN SSH============================"
echo -e "ALL SUPPORTED by Yonatan Kanu as THORN SSH"
echo -e "FB	: https://www.facebook.com/kanu.nugraha"
echo -e "WhatsApp	: 085707136028"
echo -e "Website	: http://yonatankanu.blogspot.co.id/"
echo -e "Website	: https://yonatankanu.wordpress.com/"

echo -e ""
