#!/bin/bash
#Menu

echo -e "============MENU=============="
echo -e "* menu          : menampilkan daftar perintah yang tersedia"
echo -e "* usernew       : membuat akun SSH"
echo -e "* trial         : membuat akun trial"
echo -e "* hapus         : menghapus akun SSH"
echo -e "* login         : cek user login"
echo -e "* member        : cek member SSH"
echo -e "* restart        : restart service dropbear, webmin, squid3, openvpn dan ssh"
echo -e "* reboot        : reboot VPS"
echo -e "* speedtest     : speedtest VPS"
echo -e "* bench-network : Cek Kualitas VPS"
echo -e "* ps-mem        : Cek RAM"
echo -e "* about         : informasi tentang script auto install ini"
echo -e "=========THORN SSH============="
echo -e "=======Yonatan Kanu============"
echo -e "=======WA : 085707136028======="
echo -e "===yonatankanu.wordpress.com==="
echo -e "==yonatankanu.blogspot.co.id==="
echo -e "https://www.facebook.com/kanu.nugraha"
